[general]
symbols = ["BTC/USDT"]
timeframe = "15m"
train_window = 500

[exchange]
name = "binance"
api_key = "${BINANCE_API_KEY}"
api_secret = "${BINANCE_API_SECRET}"

[logging]
sheet_type = "excel"
max_position_size = 0.01